[package]
name = "ga"
version = "0.1.0"
authors = ["Adam Jensen <acjensen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"