name: Rust

on:
  push:
    branches: [ master ]
    paths:
      - 'rust/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'rust/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd rust && cargo build
    - name: Run tests
      run: cd rust && cargo test
